Balances issues
bancorprotocol/webapp-v2 pull request #233
Opened 2021-08-01 12:06 UTC by Ran73Cohen

#195 #231 #232

2021-08-02 03:07 UTC, Velua requested changes
Lets discuss before a merge.

2021-08-09 01:13 UTC, Velua approved these changes

2021-08-09 07:12 UTC, Ran73Cohen commented on src/elements/swapMarket/SwapMarket.tsx
> +    if (!(chainId && toToken && account)) return;
If the user disconnects or switches chain after the trade we cant refresh balances
They will be fetched anyway when he switches back or change its chain

2021-08-09 07:24 UTC, Ran73Cohen commented on src/elements/swapLimit/SwapLimit.tsx
> +    const wethIndex = tokens.findIndex((x) => x.address === wethToken);
updated

2021-08-09 10:54 UTC, merged