Swap deep link
bancorprotocol/webapp-v2 pull request #286
Opened 2021-08-29 12:43 UTC by Ran73Cohen

#128

2021-08-30 12:31 UTC, pingustar commented
@Ran73Cohen I think query params are more suitable for the swap widget

2021-09-13 11:21 UTC, ashachaf commented
- [ ] update CTA to indicate token not supported 
when a user selects a token on market and then switch to limit, please do the following:
1. IF the token exists on the token list (in this case the limit order token list) -> proceed normally
2. ELSE (token is not on the list) -> update the CTA:
- disable the CTA
- identify if the token is in the from or to
- update text: "To/From token not supported"

2021-09-29 11:12 UTC, ashachaf commented
> * [x]  update CTA to indicate token not supported
>   when a user selects a token on market and then switch to limit, please do the following:
> 
> 1. IF the token exists on the token list (in this case the limit order token list) -> proceed normally
> 2. ELSE (token is not on the list) -> update the CTA:
> 
> * disable the CTA
> * identify if the token is in the from or to
> * update text: ""You Pay"/"You Receive" token is not supported"

i do not see this flow in the preview url.

2021-09-30 09:37 UTC, ashachaf commented
- [ ] unsupported token flow
1. the text on the button is not correct as it is always saying "your Pay"
2. can we use the token symbol instead in the message? for example: "USDB is not supported"
![image](https://user-images.githubusercontent.com/40430285/135425666-67c13f8d-1f9c-428c-ba29-84ac0d27d1e0.png)

- [ ] case of ETH as the "you receive" token:
1. from market to limit -> update it to WETH
2. from limit to market -> update it to ETH

- [ ] case of ETH as "you pay" token should not disable the CTA
![image](https://user-images.githubusercontent.com/40430285/135425965-2de4182c-f529-49ef-8869-7a8c0ab5f5e2.png)

2021-09-30 12:01 UTC, zavelevsky requested changes

2021-09-30 12:01 UTC, zavelevsky commented on src/elements/swapWidget/SwapWidget.tsx
> +      const url = `?from=${toToken.address}${
This is very specific application code - shouldn't take place inside a widget

2021-09-30 12:01 UTC, zavelevsky commented on src/services/observables/triggers.ts
> +    dispatch(setKeeperDaoTokens(keeperDaoTokens));
duplicate call to `setKeeperDaoTokens`

2021-09-30 12:07 UTC, Ran73Cohen commented on src/elements/earn/pools/poolsTable/PoolsTableCellActions.tsx
> +    (x) => x.address !== bntToken(chainId ? chainId : EthNetworks.Mainnet)
Its just two reserves but yeah will place it outside

2021-09-30 12:07 UTC, Ran73Cohen commented on src/elements/earn/pools/poolsTable/PoolsTableCellActions.tsx
> +  console.log('tknAddress', tknAddress);
Thanks! forgot to

2021-09-30 12:12 UTC, Ran73Cohen commented on src/elements/earn/pools/poolsTable/PoolsTableCellActions.tsx
> +        to={tknAddress ? `/?from=${tknAddress}` : '/'}
End slashes are removed from route by default, I can link to an empty route but when redirecting to root it is general practice to use /

2021-09-30 12:13 UTC, Ran73Cohen commented on src/elements/swapLimit/SwapLimit.tsx
> +      return 'You Pay token is not supported';
Its like "You pay" as In the field but we changed it to the symbol itself

2021-09-30 12:14 UTC, Ran73Cohen commented on src/elements/swapLimit/SwapLimit.tsx
> +    if (
I agree, you can open an issue about swap limit and swap market

2021-09-30 12:16 UTC, Ran73Cohen commented on src/elements/swapWidget/SwapWidget.tsx
> +    if (!fromToken) history.push(limit ? '?limit=' + limit : '');
Well thats the point of this task to create the deep link based on the tokens the user selects

2021-09-30 12:16 UTC, Ran73Cohen commented on src/services/observables/triggers.ts
> +    dispatch(setKeeperDaoTokens(keeperDaoTokens));
stale

2021-10-05 08:47 UTC, ashachaf commented
minor fix:
- [ ] switching between market to limit - carry the user input value
flow:
- open market
- select from/to tokens
- input value in the from token field
- switch to limit view
expected: keep the input value when switching to the limit view. 

- [ ] CTA text to connect a wallet
on market, we have a logical flow that shows "connect a wallet" text on the CTA if the user did not connect a wallet.
however, on limit, the text is "trade" and doesnt follow the same logic.
expected:
- limit and market should follow the same CTA text logic when user wallet not connected, tokens are not selected and no input amount.

2021-10-05 09:52 UTC, merged