set default provider if no alchemy key found
bancorprotocol/webapp-v2 pull request #420
Opened 2021-11-19 10:49 UTC by pingustar

#404

2021-11-21 11:36 UTC, zavelevsky approved these changes

2021-11-21 13:19 UTC, RanCohenn requested changes
SetProvider also needs to be handled when switching networks

2021-12-17 15:28 UTC, pingustar commented
> SetProvider also needs to be handled when switching networks

this feature is in conflict with the latest efforts of the websocket keepAlive code. @RanCohenn do you mind taking a look at this, maybe it is a quick one for you. If no quickie ... lets close this PR for now.

2021-12-20 08:36 UTC, RanCohenn approved these changes

2021-12-20 12:02 UTC, merged